Cray-HPE/config-framework-service

- api/openapi.yaml
- src/server/cray/cfs/api/controllers/components.py
- src/server/cray/cfs/api/controllers/sessions.py
Adds a parameter to CFS to allow sessions to be created with arbitrary arguments passed to Ansible
* Resolves CASMCMS-7784
* Wasp
Ran CFS sessions without passthrough parameters, and with different combinations of parameters.
None
> CASMCMS-7784: Add Ansible passthrough parameter

- kubernetes/cray-cfs-api/values.yaml
Adds anit-affinity to the CFS api pods.  CFS uses an autoscaler to determine the number of pods, so the anti-affinity is "preferred" not "required" so that scaling isn't capped by the number of nodes.
* Resolves CASMINST-3913
* Hela
- Deployed with multiple pods and confirmed that they were on different nodes.
None
> CASMINST-3913: Add pod antiaffinity

- kubernetes/cray-cfs-api/values.yaml
Update the database image from redis:5.0-alpine3.12 to redis:5.0-alpine.  This less specific tag allows use of more recent alpine base images that are still being patched for security vulnerabilities.  The current version uses alpine:3.15 and has the security issues resolved.
* Resolves [CASMCMS-7823](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7823)
* Change will also be needed in `cray-bos`
* Merge with `https://github.com/Cray-HPE/bos/pull/30`
* `Mug`
* Local development environment
I verified the new image is clean using the SNYK scanner.  After building a new version of cray-cfs-api using the new database image, I updated the deployment on Mug, verified the db was working correctly, then rolled back to the original version.
- Were the install/upgrade-based validation …
> CASMCMS-7823 - Update redis image to alpine:3.15 base image to resolve security issues.

- kubernetes/cray-cfs-api/Chart.yaml
Change the chart annotations to match the actual redis image used. This impacts the images that are packaged in a release and what is scanned for CVE vulnerabilities. It does not impact the actual use of the service.
* Resolves [CASMCMS-7965](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7965)
* `Wasp`
Installed the new version with loftsman, ran the ct tests (successfully), reverted back to the original install, then re-ran the ct tests to insure everything is still working correctly.
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? Y
- Were continuous integration tests run? If not, why? Y
- Was upgrade tested? If not, why? Y
- Was downgrade tested? If not, why? Y
- Were new tests (or test issues/Jiras) created for this change? N …
> CASMCMS-7965 - Fix chart annotation for version of redis image being used.

- Dockerfile
- kubernetes/cray-cfs-api/Chart.yaml
Change the chart annotations to match the actual redis image used.  This impacts the images that are packaged in a release and what is scanned for CVE vulnerabilities.  It does not impact the actual use of the service.
I have also changed the location of the alpine base image to use the one that is being patched nightly for CVE remediations.  This is the same image, just a different location and will automatically incorporate new security fixes.
* Resolves [CASMCMS-7965](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7965)
* `Wasp`
Installed the new version with loftsman, ran the ct tests (successfully), reverted back to the original install, then re-ran the ct tests to insure everything is still working correctly.
- Were the install/upgrade-based validation checks/tests run (goss …
> Casmcms 7965

- src/server/cray/cfs/api/controllers/components.py
Fixes an issue with tag cleanup that was affecting BOS v2 in rare cases
* Resolves CASMCMS-7945
* Mug
Deployed the fix with BOS v2 and confirmed that the tag cleanup was working correctly when triggered by BOS.  Also tested manually.
None
> CASMCMS-7945: Fix component tag cleanup

- Dockerfile
- requirements.txt
The 'dev.cray.com' domain is being retired and the servers moved to hpe domains.  This PR removes references to servers on this domain where able, and updates to the new hpe addresses where we still need to reference internal servers.  There are no real code changes - should just be pulling the same packages from different locations.
* Resolves [CASMCMS-7971](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7971)
* `Mug`
The new versions of all services are installed on Mug and are being left in place while Jason does Bos v2 testing to give these a complete workout.
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? Y
- Were continuous integration tests run? If not, why? Y
- Was upgrade tested? If not, why? Y
- Was downgrade tested? If …
> CASMCMS-7971 - update dev.cray.com addresses.

- CHANGELOG.md
- kubernetes/cray-cfs-api/templates/database.yaml
- kubernetes/cray-cfs-api/values.yaml
Escalates the pods to a high priority to improve CFS' ability to run when the system is partially down.
* Resolves CASMTRIAGE-3835
* Mug
Deployed the new image chart and tested basic functions
None
> CASMTRIAGE-3835: Escalate pod priority

- CHANGELOG.md
- kubernetes/cray-cfs-api/templates/database.yaml
- kubernetes/cray-cfs-api/values.yaml
_Summarize what has changed. Explain why this PR is necessary. What is impacted? Is this a new feature, critical bug fix, etc?_
The cray-cfs-api chart does not have overrides for the PVC storage class so the override was added. This is a bug fix
_Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix?_
Can helm rollback.
_List and characterize relationship to Jira/Github issues and other pull requests. Be sure to list dependencies._
* Resolves [issue id](issue link) https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7863
_List the environments in which these changes were tested._
Mug
Ran helm deploy with updated image and template
_How were the changes tested and success verified? If schema changes were part of this change, how were those handled …
> adding pvc override hotfix, update CHANGELOG

- CHANGELOG.md
- kubernetes/cray-cfs-api/Chart.yaml
- update_versions.conf
update_versions.conf was pulling the chart and Docker version strings from the .version file, rather than the .docker_version and .chart_version files. This meant that it always was using the a.b.c version string, omitting any extra fields. This PR modifies it so that the Chart is updated with the actual Docker and chart version strings. For stable artifacts on the master branch, this will be no change, but this will allow (for example) stable beta artifacts to retain the beta string in their versions.
None beyond making sure the build works and the artifacts get the correct version strings.
Extremely high risk. Incalculable.
> CASMCMS-8252: Update Chart with correct image and chart version strings during builds

- CHANGELOG.md
- api/openapi.yaml
- kubernetes/cray-cfs-api/Chart.yaml
- kubernetes/cray-cfs-api/values.yaml
- update_versions.conf
Currently the Chart.yaml and values.yaml files are hard-coded to point to stable directories on artifactory. The problem comes if an unstable artifact is built. That version of the docker image won't exist in that location out on artifactory, making the unstable chart unusable.
The fix is to adjust the path to stable or unstable based on the type of build being done. This was done in the BOS repo with this PR:
https://github.com/Cray-HPE/bos/pull/57
This PR does the same thing for the CFS repository.
I also noticed that there was an unintentional string replace happening in openapi.yaml during the builds:
```text
13:55:33  update_versions.sh: Replacing version tags (0.0.0) in api/openapi.yaml
13:55:33  update_versions.sh: # diff "api/openapi.yaml.after" "api/openapi.yaml"
13:55:33  28c28 …
```
> CASMCMS-8089: Enable building of unstable artifacts

- CHANGELOG.md
- api/openapi.yaml
In a craycli PR, I did some linting of the CFS CLI text, and noticed some things to clean up in the API spec as well. No content changes -- just minor language cleanup in the API spec file.
* [Cray CLI PR](https://github.com/Cray-HPE/craycli/pull/65)
* Resolves [CASMCMS-8380](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8380)
Extremely low -- only minor changes made to description text fields in the API spec.
> CASMCMS-8380: Linting of openapi spec file (no content changes)

- CHANGELOG.md
- config/uwsgi.ini
Quadruple uwsgi's buffer size, so it can handle larger request headers. The nodes come in as query parameters, so these bloat the request when there are a lot of them. This is usually do to system size and requests targeting larger numbers of nodes.
_Summarize what has changed. Explain why this PR is necessary. What is impacted? Is this a new feature, critical bug fix, etc?_
_Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix?_
_List and characterize relationship to Jira/Github issues and other pull requests. Be sure to list dependencies._
* Resolves [issue id](issue link)
* Change will also be needed in `<insert branch name here>`
* Future work required by [issue id](issue link)
* Documentation changes required in [issue id](issue link)
* Merge …
> CASMCMS-8494: Quadrupling uwsgi's buffer size

- CHANGELOG.md
- constraints.txt
Pin the `cryptography` module to a version that fix this CVE:
https://security.snyk.io/vuln/SNYK-PYTHON-CRYPTOGRAPHY-5777683
* Resolves [CASMCMS-8718](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8718)
* [support/1.12 backport PR](https://github.com/Cray-HPE/config-framework-service/pull/73)
* Similar fixes have been and are being made in other repos:
* `cfs-operator`: [CASMCMS-8715](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8715)
* `ansible-execution-environment`: [CASMCMS-8717](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8717)
On mug, I deployed cray-cfs and cray-cfs-operator using the CVE fixes contained in the following 3 PRs:
* https://github.com/Cray-HPE/ansible-execution-environment/pull/40
* https://github.com/Cray-HPE/config-framework-service/pull/72
* …
> CVE: CASMCMS-8718: Update version of cryptography dependency

- CHANGELOG.md
- constraints.txt
Updated the jsonschema dependecny to address a bug in openapi-schema-validator
* Resolves [CASMCMS-8772](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8772)
* Resolves [CASMTRIAGE-5948](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-5948)
* Mug
Deployed, verified migration happened, tested functionality after migration
None
> CASMCMS-8772: Update jsonschema version

- CHANGELOG.md
- api/openapi.yaml
Adds an ims_job field to session status to allow tracking and cleanup of the IMS jobs created for image customization.
* Resolves CASMCMS-8789
* Mug
Verified the ims_job field exists and was being written to by the cfs-operator
None
> CASMCMS-8789: Add ims_job field to session status

- CHANGELOG.md
- src/server/cray/cfs/api/controllers/components.py
Fixes a bug introduced by the v3 code changes that causes failed and incomplete layers to be incorrectly marked as configured when aggregating status.
* Resolves CASMTRIAGE-6032
* Mug
Setup a component with the problem state and validated the the status was correctly calculated after updating the api.
None
> CASMTRIAGE-6032: Fix component layer status handling

- CHANGELOG.md
- src/server/cray/cfs/api/controllers/sessions.py
Fixes a bug introduced by the v3 code that was making it impossible to create sessions using the v2 endpoint with configuration names longer than the limit imposed on that field in the v3 api.
* Resolves CASMTRIAGE-6041
* Mug
Tested commands that were previously failing and compared the behaviors of the v2 and v3 apis.
None
> CASMTRIAGE-6041: Fix v2 sessions with long configuration names

- CHANGELOG.md
- src/server/cray/cfs/api/controllers/sessions.py
Fixes an issue introduced by the workaround for long configuration names, that was causing sessions to use the wrong configuration when creating v2 sessions.
* Resolves CASMTRIAGE-6158
* beau
Successfully created a v2 session with the correct configuration using a command that had previously been failing.
None
> CASMTRIAGE-6158: Fix v2 session creation

- CHANGELOG.md
- Dockerfile
- api/openapi.yaml
- kubernetes/cray-cfs-api/values.yaml
- requirements.txt
- src/server/cray/cfs/api/controllers/configurations.py
- src/server/cray/cfs/api/controllers/options.py
- src/server/cray/cfs/api/controllers/sources.py
- src/server/cray/cfs/api/dbutils.py
- src/server/cray/cfs/api/vault_utils.py
Adds "sources" to the CFS API.  This allows users to specify repos, as well as their credentials and ca certs, so that CFS can access Ansible content outside the standard VCS.
Also includes a new option to drop the branch field from configurations after converting it to a commit
* Resolves CASMCMS-8790
* Resolves CASMCMS-8794
* Mug
- Tested updating, patching and deleting various sources.
- Tested adding configurations with branches, with and without sources (so the branch was converted in the API)
- Tested CFS sessions using configurations with and without sources.
None
> CASMCMS-8790: Add sources to the CFS api

- CHANGELOG.md
- src/server/cray/cfs/api/controllers/configurations.py
Fixes a bug when trying to covert the branch to commit when using the additional_inventory field in a a configuration.
* Resolves CASMTRIAGE-6403
* Mug
Validated the test case that had been failing
None
> CASMTRIAGE-6403: Fix branch conversion for additional inventory

- CHANGELOG.md
- src/server/cray/cfs/api/dbutils.py
The `patch_all` method in `dbutils` accidentally omitted a `self.` when trying to call a database function, so it accidentally was trying to use the Kubernetes Python module. This did not work well, and breaks one of the v3 components patching paths.
I am making this PR against my other development branch because I want to test the fixes together.
* Resolves [CASMCMS-8888](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8888)
The fix looks good. The operation does still fail, though, but now it is for the reason I expected -- the one I am pursuing with [CASMCMS-8887](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8887)
Low risk -- the function is broken as is.
> CASMCMS-8888: Correct accidental use of Kubernetes Python client insead of DB client in patch_all method

- CHANGELOG.md
- src/server/cray/cfs/api/dbutils.py
The v3 multi-session delete and v3 multi-component patch endpoints can succeed but return 500 status codes because they try to return a list of bytes, and those are not JSON serializable. This PR decodes the bytes into UTF-8 strings, preventing this problem.
This PR is deliberately against another dev branch, because I want to test them together.
* Resolves [CASMCMS-8887](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8887)
* Related to [CASMCMS-8888](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8888)
With this fix in place, both the patch multi-updates and the session multi-deletes work as they should.
Low risk -- without this, these return calls only work when the lists are empty.
> CASMCMS-8887: Decode IDs from bytes to UTF-8 strings in patch_all/delete_all methods

- CHANGELOG.md
- src/server/cray/cfs/api/controllers/sessions.py
Fixes the link for ARA returned with session data
* Resolves CASMCMS-8920
* Mug
Verified the API output and that it linked to the expected page.
None
> CASMCMS-8920: Fix ARA link for sessions

- CHANGELOG.md
- api/openapi.yaml
This corrects several errors I found when reviewing the CFS API spec recently:
* Several `description` fields have minor errors (usually seemed to be copy-paste errors when the schema was created based on another schema). A couple of `example` fields had the same issue.
* The `Version` schema claims that the `major`, `minor`, and `patch` fields are integers, but in truth CFS has always returned them as string values. Looking at the source code, I can see why. Given that CFS has always behaved this way, it seems better to update the API spec to reflect reality, rather than change the API behavior.
* The version endpoints claim (in `summary` and `description` texts) that they return lists of versions, but in truth they just return the current version.
* For paginated responses, the `next` …
> CASMCMS-8959: Correct errors in API spec

- CHANGELOG.md
- src/server/cray/cfs/api/controllers/components.py
This fixes a very simple bug in the `patch_v2_components_dict` function. The loop at its end is supposed to be updating each component that has been identified. However, it uses the wrong variable for the component ID, causing it to just update the same component over and over. We can see this because if we call CFS to patch 100 components using this function, we get back a response that shows it patched a single component 100 times.
Looking at the companion function `patch_v2_components_list`, I assume there was just some confusion that led to this bug. I made a fix that makes the two functions more closely parallel each other, since I think there subtle differences are what led to this bug in the first place. Hopefully by making them follow each other more closely, it will make future …
> CASMTRIAGE-6865: Fix bug in patch_v2_components_dict that causes only a single component to be updated

- CHANGELOG.md
- src/server/cray/cfs/api/controllers/components.py
This addresses Jason's astute review comment: https://github.com/Cray-HPE/config-framework-service/pull/116#discussion_r1554289984
Note that this will require backports to the newer versions, because this problem existed in Ryan's fix to this bug as well:
https://github.com/Cray-HPE/config-framework-service/pull/122
https://github.com/Cray-HPE/config-framework-service/pull/123
> CASMCMS-8962: Properly handle response from DB.get_all

- CHANGELOG.md
- api/openapi.yaml
- constraints.txt
I noticed some CFS errors being logged in Kubernetes, but saw no associated problems being caused by them. The errors I saw were:
```text
ERROR   - connexion.operations.openapi3 - Body property 'stateAppend' not defined in body schema
```
I tracked it down a bug in the `connexion` Python module I found the version we need to go to to pick up the fix for it. I've reviewed the changelog and I don't see any breaking changes that will impact us, and I tested the changes on wasp and verified that is resolves the issue, that the `cmsdev` CFS test suite passes, and that a CFS session I ran succeeded without incident.
> CASMCMS-8964: Bump connexion version to prevent false schema errors being logged

- CHANGELOG.md
- api/openapi.yaml
When v3 was introduced, the new special parameters option was overlooked, as it was being developed in parallel. This PR adds it back to the schema, which Ryan B believes should be all we need to do.
Without this change, the V3 API will reject attempts to create configurations that have layers with special parameters. However, this can be worked around by creating them using the V2 API. Once they are created, even without this fix, when you describe or list CFS configurations using V3, it displays the special parameters.
On mug, with the fix in place, I've verified that creating the configuration using V3 works fine.
> CASMCMS-8966: Add missing special_parameters property to V3ConfigurationLayer schema

- CHANGELOG.md
- kubernetes/cray-cfs-api/templates/database.yaml
When the "cray-cfs-api" chart was converted to non-root, the change was incomplete.  In addition to specifying a "securityContext" for the container, a "securityContext" also needs to be specified for the pod.  This is what tells Kubernetes how to set up permissions on PVCs.  Without that, the PVCs will have the default permissions of the underlying storage class, which can vary between storage classes.
The only reason things are currently working is because the CephFS storage class defaults to a top level directory of "root/root", mode "0x777".  In Mercury we switch to a cStor storage class, where the default permissions are "0x755", and non-root containers are not able to create files.
* Resolves [CASMCMS-8060](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8060)
* Mercury
Without this …
> CASMCMS-8060 Fix incomplete non-root cray-cfs-api changes

- CHANGELOG.md
- src/server/cray/cfs/api/controllers/components.py
The fix for [CASMTRIAGE-5974](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-5974) modified the `_matches_filter` function in `src/server/cray/cfs/api/controllers/components.py`, adding the `id_list` argument. (PR: https://github.com/Cray-HPE/config-framework-service/pull/82). However, it overlooked the call to this function in the `patch_v2_components_dict` function. So now that function raises an exception when it tries to make that call, due to the omitted argument.
Originally, this PR just modified the call so that it included all of the required arguments. But while that did allow my PATCH requests to succeed, I noticed that they were modifying more components than they should be. This led me to discover that there is a bug in the status filtering code for v2 -- specifically, the …
> CASMCMS-8978: Fix broken _matches_filter call in patch_v2_components_dict

- CHANGELOG.md
- constraints.txt
- kubernetes/cray-cfs-api/Chart.yaml
Per the PET team, we need to move up to this version in CSM 1.6 or we'll be broken. I installed this on mug and saw no problems.
I also had to bump some dependency versions to calm Snyk down.
> CASMCMS-9005: Bump minimum cray-services base chart version

- CHANGELOG.md
- api/openapi.yaml
No changes to fields that impact the service itself -- only to informational fields.
> CASMCMS-9055: Update API spec to reflect the actual allowed formats for the age/TTL field

- CHANGELOG.md
- api/openapi.yaml
When working on [this cfs-operator PR](https://github.com/Cray-HPE/cfs-operator/pull/125), I noticed that CFS requires the TTL and age fields to follow a particular format in order to work. However, the API spec doesn't enforce this. So users are allowed to set bad values, and will only find out when they don't see the desired behavior. This change updates the spec so that these issue will be caught when the bad values are used.
I also noticed that the API spec only mentioned days and hours as valid units, but the actual code also allows for minutes and weeks. So I modified the spec to reflect the actual code behavior.
If a user has already set an invalid value for one of these options and then upgrades to this version of CFS, they'll still be able to keep that illegal value. But if they …
> CASMCMS-9055: Update API spec to reflect the actual requirements and format for the age/TTL fields

- CHANGELOG.md
- api/openapi.yaml
[CASMTRIAGE-7462](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-7462) was opened because a CFS component ended up being created with an empty string as its ID, and this caused issues. There are several aspects to this problem, and this PR addresses one of them. Specifically, it corrects some errors in the CFS API spec, one of which led to the described problem being possible.
1. When doing a PUT request to the `/components` endpoints, the spec allowed you to specify components whose ID fields were set to 0 length strings. This is how the problem described earlier came about. This PR updates the spec so that the ID field is a non-0 length string. Note that the spec still allows for the field to be omitted entirely. This is okay, because:
1. The code that handles creating components …
> CASMCMS-9189: Component-related corrections to API spec

- CHANGELOG.md
- src/server/cray/cfs/api/controllers/sources.py
If you try to use the CFS API to create a source without specifying the `authentication_method` field, CFS hits an exception. CFS assumes that because the API spec sets a default value for this field, that connexion will automatically set it if needed. This is not the case. connexion validates the request body against the schema, but it does not set default values. This PR adds code to set the default value for this field, if it is omitted. I tested these changes on mug and verified that they correct the problem.
For CSM 1.7 I want to make a more general fix for this, where for any incoming request body, we consult the spec and fill in defaults as needed. I already have a simple function to do this, but even though it's simple, it's not as simple as the tiny change in this PR. For the CSM …
> CASMCMS-9196: Use default value for authentication_method when creating a source, if not specified

- CHANGELOG.md
- src/server/cray/cfs/api/controllers/configurations.py
- src/server/cray/cfs/api/controllers/sources.py
Currently, when asking CFS to list sources or configurations, CFS will always calculate the list of sources or configurations that are in use, whether or not you are filtering on that basis. On systems with a large number of CFS components, this can add almost a minute to the request time. This PR modifies the code so that the in_use lists are only created when they are actually necessary. I have tested on mug and verified that this reduces the huge performance penalty when listing without that filter specified, but that it does not break the ability to filter on that basis.
> CASMCMS-9197: Only calculate in_use list if needed

- CHANGELOG.md
- api/openapi.yaml
Currently, for options that exist in both CFS v2 and v3, the API spec places more restrictions on the values that options can take in v3. I discovered this when the v2 endpoint let me set the logging level to 'debug', which is not a valid value per the V3 spec. This then caused CFS to hit a CLBO.
This PR modifies the API spec so that the V2 options follow the same value restrictions as the V3 options (for those that exist in both). I have tested this on mug and verified that it resolves the problem described (by preventing invalid values from being set).
> CASMCMS-9198: Enforce same value restrictions on CFS options between v2 and v3 (for options that exist in both)

- CHANGELOG.md
- src/server/cray/cfs/api/controllers/options.py
While doing other work, I noticed occasional Exceptions in the CFS server pod logs.  It was a `TypeError` generated by [this line of code](https://github.com/Cray-HPE/config-framework-service/blob/e3f3702bbda61f06674a7577520ef54968e43c66/src/server/cray/cfs/api/controllers/options.py#L152).
The specific error was:
`TypeError: 'NoneType' object is not subscriptable`
That got me looking at the `Options` class, and I started to suspect some thread safety issues, possibly related to the singleton implementation. There definitely is a possible race condition that results in more than one thread getting into the critical block in the `__new__` method. But even aside from that, it still ends up calling the `__init__` method every time the class is instantiated, even though it is a singleton. …
> CASMCMS-9200: Make Options class thread-safe and prevent redundant initialization

- CHANGELOG.md
- api/openapi.yaml
- src/server/cray/cfs/api/controllers/sources.py
When a Source is created using CFS v3, it takes a specified username and password, saves them under a Vault secret, and then resulting CFS source listing has that Vault secret name, not the username and password.
However, there is currently no way to create a source in CFS and specify the Vault secret name instead of the username and password. For regular use, this makes sense, but this ability is needed for the backup/restore case. I discussed this with Ryan and he agreed this isn't possible without modifying the API.
At first I considered just updating the current endpoint used to create sources, and having it allow either case. The only downside for that the two code paths are fairly different -- a lot of things are required for the create code path that are superfluous for the restore …
> CASMCMS-9202: Add POST option to v3/sources/{source_id} endpoint

- CHANGELOG.md
- api/openapi.yaml
All layers (whether additional or normal) in CFS v3 require either clone_url or source to be set, but not both. The CFS server code makes this clear (and I have confirmed with Ryan). The spec, however, for additional inventory layers in v3, states that the clone_url field is required. This has the effect of making it impossible to create a configuration with an additional inventory layer that contains a source field. If you try to specify both source and clone_url, then the server balks. If you try to specify just source, then connexion stops you, because it violates the spec.
This PR updates the spec to remove the requirement for clone_url specifically, and also updates the V3 layer descriptions to explicitly state that the fields are mutually exclusive, but one is required.
I have …
> CASMCMS-9206: Update API spec to reflect that in v3, a layer requires exactly one of clone_url and source

- CHANGELOG.md
- src/server/cray/cfs/api/controllers/configurations.py
When a CFS configuration is deleted, it checks to make sure it is not in use before deleting it. The method it uses to do this is to look at every component and make a list of every configuration that is in use, and then see if this particular configuration is in that list. This has the virtue of reusing code, but it can take a long time. On a large scale system like mug, the delete operation took over 35 seconds.
This PR improves that procedure in two ways:
1. Instead of listing all components, it queries specifically for components that have that particular configuration as their desired configuration. This means that the filtering for relevant components happens much closer to the database calls.
2. When doing that query, set a limit of 1. That means that CFS will respond to us after …
> CASMCMS-9211: Improve performance of configuration delete operation

- CHANGELOG.md
- kubernetes/cray-cfs-api/templates/api-autoscaler.yaml
Per @studenym-hpe , we need to update this `apiVersion` in order to work with the upgraded Kubernetes in CSM 1.7.
> CASMCMS-9150: Update API autoscaler apiVersion to support upgraded Kubernetes in CSM 1.7

- CHANGELOG.md
- src/server/cray/cfs/api/controllers/components.py
- src/server/cray/cfs/api/dbutils.py
On mug (~12000 nodes), I noticed that CFS batcher was not creating CFS sessions. Investigation revealed that it was hitting repeated timeouts when trying to query CFS for components. Even drastically lowering the page size did not fix the issue. Looking closer, I think this is similar to something I needed to change in BOS when I implemented paging there. Specifically, I had to change how it scanned through the Redis database. Currently CFS does individual DB gets for each component. This leads to it being very slow. Grabbing them in batches significantly improves performance.
I also noticed that the filter function sets the component status even before it needs to. A number of the filter options are ones which are un-impacted by the status update functions. Thus, we should only call the …
> CASMCMS-9263: Improve CFS component query performance

- src/server/cray/cfs/api/dbutils.py
This PR makes sure that the `develop` branch has the bug fix for this syntax error.
This bug does not exist in `master` branch, so I think it would be more confusing than anything else to add this to the CHANGELOG, because then it would look like version v1.25 has this bug, when it does not.
The current theory is that since Joel and I were both making changes to that same file, one of us made a mistake when resolving merge conflicts, resulting in this bug going into develop but not being there in master.
> CASMCMS-9280: Fix syntax error in get_all method of dbutils

- CHANGELOG.md
- src/server/cray/cfs/api/controllers/configurations.py
In [the original PR that added tenancy support](https://github.com/Cray-HPE/config-framework-service/pull/167), the behavior of the v3 configuration PATCH endpoint was changed in a way that inappropriately altered how it behaved. This was [reverted in a later PR](https://github.com/Cray-HPE/config-framework-service/pull/179), but that PR also accidentally removed similar code from the v3 configuration PUT endpoint. That removal broke the ability to create configurations that are associated with tenants. This PR restores that accidentally-removed block of code.
> CASMCMS-9461: Restored accidentally-removed tenancy code

- CHANGELOG.md
- api/openapi.yaml
When tenancy support was added to the v3 configuration endpoints, it added new possible error responses to the endpoints -- 400 in the case that the tenant did not exist, and 403 in the case that the requested operation is forbidden. This PR updates the API spec to reflect that.
> CASMCMS-9464: Document new API error responses introduced with tenancy support

- CHANGELOG.md
- src/server/cray/cfs/api/dbutils.py
This PR is deliberately not against the `develop` branch.
I am going to work on CASMCMS-9538 incrementally, using self-contained subtasks, corresponding to Jiras like this one. Each PR will be adding to the `casmcms-9538` branch, and when we're ready, I'll merge that all into `develop`.
The main symptom reported in CASMCMS-9538 was that some CFS GET requests included null values in the list of resources. This was causing the SAT tests to intermittently fail. This PR will resolve that specific issue, but there are a number of other race conditions in the code, some of which could cause other problems for the SAT tests, or even for customers.
* https://jira-pro.it.hpe.com:8443/browse/CASMCMS-9538
* https://jira-pro.it.hpe.com:8443/browse/CASMCMS-9544
Ongoing
Low risk. BOS and CFS share a …
> CASMCMS-9553: Do not yield missing entries from DBWrapper.iter_values

- CHANGELOG.md
- src/server/cray/cfs/api/controllers/sessions.py
- src/server/cray/cfs/api/dbutils.py
Redis has an operation which atomically gets and deletes a DB entry. The session delete endpoint needs to use this in order to avoid a race condition where another thing deletes the session between the get and the delete. This PR adds this method to the DB wrapper, and then modifies the session delete endpoints to use it.
I ran tests creating and deleting sessions on wasp, using these endpoints, and verified that they worked fine and no errors were logged in the pods.
Low risk -- we already use this DB operation in BOS, and there is nothing tricky about it. The two cases where we are using it here are very simple and unlikely to produce unexpected behavior.
> CASMCMS-9559: Add get_delete to DBWrapper

- CHANGELOG.md
- src/server/cray/cfs/api/controllers/components.py
- src/server/cray/cfs/api/controllers/configurations.py
- src/server/cray/cfs/api/dbutils.py
This does not directly address a race condition, but the current implementation of the CFS v2 multi-component patch endpoint is going to make it more difficult to fix their race condition issues.
This PR refactors `dbutils` so that most of the `patch_all` logic moves into the new `patch_all_entries` generator method (and the `patch_all` method just calls it). The reason for this is that the `patch_all_entries` generator yields both the patched entry and its DB key (which is the CFS ID of the object). For V3 multi-patch, it only cares about returning the ID, but for V2, it wants to return the entire patched entry. Making this change in `dbutils` then enables the V2 `components_dict` function to use similar logic to the V3 `components_dict` function, only using the new DB generator method …
> CASMCMS-9562: Consolidate back-end code for multi-component-patch endpoints

- CHANGELOG.md
- src/server/cray/cfs/api/dbutils.py
This PR defines two new database-related exceptions for CFS, and adds helper methods in the `DBWrapper` class to create them for that particular database. This PR does not yet make any use of these exceptions. Other than a minor refactoring of how the `DBWrapper` class is initialized, this PR does not change the current CFS logic at all, and is functionally transparent.
I separated this into its own PR because the PR where I am going to make use of them is going to involve several things, and I wanted to try to focus it as much as possible.
The `DBNoEntryError` exception will be what the DB methods raise in a case where an entry does not exist, but the caller expected it to. Currently all of that logic is happening in the controller methods, but that leads to race condition problems …
> CASMCMS-9564: Create DBNoEntryError and DBTooBusyError exceptions

- CHANGELOG.md
- src/server/cray/cfs/api/controllers/components.py
- src/server/cray/cfs/api/controllers/configurations.py
- src/server/cray/cfs/api/controllers/options.py
- src/server/cray/cfs/api/controllers/sessions.py
- src/server/cray/cfs/api/controllers/sources.py
- src/server/cray/cfs/api/dbutils.py
This continues the work started in https://github.com/Cray-HPE/config-framework-service/pull/200, this time for the `DB.get` method.
This PR modifies that method so that it now raises `DBNoEntryError` when the entry does not exist (instead of returning None). 
And of course it modifies all callers of the method, to make sure they correctly handle the exception.
In addition, the DB.patch and DB.put methods are modified so that they do not call DB.get to produce their return values. Instead, they just return the data was written to the database. The calling code clearly does not assume that DB.put or DB.patch will ever return None (which is what currently would happen if an entry was deleted immediately after being PUT or PATCHed). So this change seems to be in line with what the original …
> CASMCMS-9568: Update DBWrapper get calls to use DBNoEntryError
